export const TICKET = "DETECT_TICKET_HONGREN_BUFFETT";
export const SERVER_URL = "http://localhost:3001";
// 체크할 코인 리스트
export const DETECT_COIN_LIST = [
  "KRW-ETH",
  "KRW-NEO",
  "KRW-MTL",
  "KRW-LTC",
  "KRW-STRAT",
  "KRW-XRP",
  "KRW-ETC",
  "KRW-OMG",
  "KRW-SNT",
  "KRW-WAVES",
  "KRW-XEM",
  "KRW-QTUM",
  "KRW-GNT",
  "KRW-LSK",
  "KRW-STEEM",
  "KRW-XLM",
  "KRW-ARDR",
  "KRW-KMD",
  "KRW-ARK",
  "KRW-STORJ",
  "KRW-GRS",
  "KRW-VTC",
  "KRW-REP",
  "KRW-EMC2",
  "KRW-ADA",
  "KRW-SBD",
  "KRW-POWR",
  "KRW-BTG",
  "KRW-ICX",
  "KRW-EOS",
  "KRW-STORM",
  "KRW-TRX",
  "KRW-MCO",
  "KRW-SC",
  "KRW-GTO",
  "KRW-IGNIS",
  "KRW-ONT",
  "KRW-DCR",
  "KRW-ZIL",
  "KRW-POLY",
  "KRW-ZRX",
  "KRW-SRN",
  "KRW-LOOM",
  "KRW-BCH",
  "KRW-ADX",
  "KRW-BAT",
  "KRW-IOST",
  "KRW-DMT",
  "KRW-RFR",
  "KRW-CVC",
  "KRW-IQ",
  "KRW-IOTA",
  "KRW-OST",
  "KRW-MFT",
  "KRW-ONG",
  "KRW-GAS",
  "KRW-UPP",
  "KRW-ELF",
  "KRW-KNC",
  "KRW-BSV",
  "KRW-THETA",
  "KRW-EDR",
  "KRW-QKC",
  "KRW-BTT",
  "KRW-MOC",
  "KRW-COSM",
  "KRW-ENJ",
  "KRW-TFUEL",
  "KRW-MANA",
  "KRW-ANKR",
  "KRW-NPXS",
  "KRW-TTC",
  "KRW-AERGO",
  "KRW-ATOM",
  "KRW-TT",
  "KRW-CRE",
  "KRW-SOLVE",
  "KRW-MBL",
  "KRW-TSHP",
  "KRW-WAXP",
  "KRW-HBAR",
  "KRW-MED",
  "KRW-MLK",
  "KRW-STPT",
  "KRW-ORBS",
  "KRW-VET",
  "KRW-CHZ",
  "KRW-PXL",
];
// 체크할 최근 거래내역 리스트갯수
export const saveStoreStackMaximum = 100;
// 자전거래 예상체크 금액
export const checkSelfTradePrice = 3000;
// 리스트 중 반복되는 자전거래가 몇 개 였는지 체크
export const checkSelfTrade = 60;
// 현재 가격 상승률 %
export const checkTodayRise = 4;
// 1회 구입비용
export const onePayable = 50000;
